name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release -p:Version=2.0.0 -p:PackageVersion=2.0.0-dev${{ github.sha }} -p:RepositoryCommit=${{ github.sha }} -p:RepositoryBranch=${{ github.ref_name }}

      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          retention-days: 1
          name: build_${{ github.sha }}
          path: |
            out/*
            README.md
            LICENSE
          if-no-files-found: error

  pre-release:
    name: "Pre Release"
    needs: [build]
    runs-on: "ubuntu-latest"

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build_${{ github.sha }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            out/*
            README.md
            LICENSE
