name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1

      - name: Setup Nuget
        uses: nuget/setup-nuget@v1
        with:
          #nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: 'latest'

      - name: Restore nuget packages
        run: msbuild -t:restore

      - name: Build
        run: msbuild -t:rebuild -property:Configuration=Release -p:PackageVersion=1.1.0-dev${{ github.sha }} -p:RepositoryCommit=${{ github.sha }} -p:RepositoryBranch=${{ github.ref_name }}

      - name: Test
        run: vstest.console.exe Asap2.Tests\bin\Release\Asap2.Tests.dll

      - name: Upload nuget package
        uses: actions/upload-artifact@v2
        with:
          path: out
          if-no-files-found: error

